<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U2R40G8" failures="1" tests="10" name="Default test" time="107.948" errors="0" timestamp="2024-01-13T19:46:32 IST">
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="incorrect_login_id" time="4.074"/>
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="invalid_login_id" time="6.403"/>
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="invalid_password" time="8.436"/>
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="valid_login" time="3.802"/>
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="valid_login" time="4.01">
    <failure type="java.lang.AssertionError" message="Login unsuccessful. URL does not match the expected URL for username: locked_out_user expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: Login unsuccessful. URL does not match the expected URL for username: locked_out_user expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.Ecommerce.testCases.LoginPageTest.valid_login(LoginPageTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- valid_login -->
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="valid_login" time="3.942"/>
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="valid_login" time="11.795"/>
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="valid_login" time="4.222"/>
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="valid_login" time="3.818"/>
  <testcase classname="com.Ecommerce.testCases.LoginPageTest" name="valid_password" time="3.861"/>
</testsuite> <!-- Default test -->
